/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternalRouteImport } from './routes/_internal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as InternalSettingsRouteImport } from './routes/_internal/settings'
import { Route as InternalOverviewRouteImport } from './routes/_internal/overview'
import { Route as InternalMembersRouteImport } from './routes/_internal/members'
import { Route as InternalFeedbacksRouteImport } from './routes/_internal/feedbacks'
import { Route as AuthSignUpRouteImport } from './routes/_auth/signUp'
import { Route as AuthSignInRouteImport } from './routes/_auth/signIn'

const InternalRoute = InternalRouteImport.update({
  id: '/_internal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSettingsRoute = InternalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InternalRoute,
} as any)
const InternalOverviewRoute = InternalOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => InternalRoute,
} as any)
const InternalMembersRoute = InternalMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => InternalRoute,
} as any)
const InternalFeedbacksRoute = InternalFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => InternalRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/signUp',
  path: '/signUp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof AuthSignInRoute
  '/signUp': typeof AuthSignUpRoute
  '/feedbacks': typeof InternalFeedbacksRoute
  '/members': typeof InternalMembersRoute
  '/overview': typeof InternalOverviewRoute
  '/settings': typeof InternalSettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof AuthSignInRoute
  '/signUp': typeof AuthSignUpRoute
  '/feedbacks': typeof InternalFeedbacksRoute
  '/members': typeof InternalMembersRoute
  '/overview': typeof InternalOverviewRoute
  '/settings': typeof InternalSettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_internal': typeof InternalRouteWithChildren
  '/_auth/signIn': typeof AuthSignInRoute
  '/_auth/signUp': typeof AuthSignUpRoute
  '/_internal/feedbacks': typeof InternalFeedbacksRoute
  '/_internal/members': typeof InternalMembersRoute
  '/_internal/overview': typeof InternalOverviewRoute
  '/_internal/settings': typeof InternalSettingsRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/feedbacks'
    | '/members'
    | '/overview'
    | '/settings'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/signUp'
    | '/feedbacks'
    | '/members'
    | '/overview'
    | '/settings'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/_internal'
    | '/_auth/signIn'
    | '/_auth/signUp'
    | '/_internal/feedbacks'
    | '/_internal/members'
    | '/_internal/overview'
    | '/_internal/settings'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalRoute: typeof InternalRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal/settings': {
      id: '/_internal/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof InternalSettingsRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/overview': {
      id: '/_internal/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof InternalOverviewRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/members': {
      id: '/_internal/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof InternalMembersRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/feedbacks': {
      id: '/_internal/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof InternalFeedbacksRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_auth/signUp': {
      id: '/_auth/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signIn': {
      id: '/_auth/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InternalRouteChildren {
  InternalFeedbacksRoute: typeof InternalFeedbacksRoute
  InternalMembersRoute: typeof InternalMembersRoute
  InternalOverviewRoute: typeof InternalOverviewRoute
  InternalSettingsRoute: typeof InternalSettingsRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalFeedbacksRoute: InternalFeedbacksRoute,
  InternalMembersRoute: InternalMembersRoute,
  InternalOverviewRoute: InternalOverviewRoute,
  InternalSettingsRoute: InternalSettingsRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalRoute: InternalRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
