/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternalRouteImport } from './routes/_internal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as InternalVisaoGeralRouteImport } from './routes/_internal/visao-geral'
import { Route as InternalMembrosRouteImport } from './routes/_internal/membros'
import { Route as InternalFeedbacksRouteImport } from './routes/_internal/feedbacks'
import { Route as InternalEnviarFeedbackRouteImport } from './routes/_internal/enviar-feedback'
import { Route as InternalConfiguracoesRouteImport } from './routes/_internal/configuracoes'
import { Route as AuthSignInRouteImport } from './routes/_auth/signIn'
import { Route as AuthSignUpIndexRouteImport } from './routes/_auth/signUp/index'
import { Route as AuthSignUpInvitationIdRouteImport } from './routes/_auth/signUp/$invitationId'

const InternalRoute = InternalRouteImport.update({
  id: '/_internal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalVisaoGeralRoute = InternalVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => InternalRoute,
} as any)
const InternalMembrosRoute = InternalMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => InternalRoute,
} as any)
const InternalFeedbacksRoute = InternalFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => InternalRoute,
} as any)
const InternalEnviarFeedbackRoute = InternalEnviarFeedbackRouteImport.update({
  id: '/enviar-feedback',
  path: '/enviar-feedback',
  getParentRoute: () => InternalRoute,
} as any)
const InternalConfiguracoesRoute = InternalConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => InternalRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/_auth/signUp/',
  path: '/signUp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpInvitationIdRoute = AuthSignUpInvitationIdRouteImport.update({
  id: '/_auth/signUp/$invitationId',
  path: '/signUp/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signIn': typeof AuthSignInRoute
  '/configuracoes': typeof InternalConfiguracoesRoute
  '/enviar-feedback': typeof InternalEnviarFeedbackRoute
  '/feedbacks': typeof InternalFeedbacksRoute
  '/membros': typeof InternalMembrosRoute
  '/visao-geral': typeof InternalVisaoGeralRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/signUp/$invitationId': typeof AuthSignUpInvitationIdRoute
  '/signUp': typeof AuthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signIn': typeof AuthSignInRoute
  '/configuracoes': typeof InternalConfiguracoesRoute
  '/enviar-feedback': typeof InternalEnviarFeedbackRoute
  '/feedbacks': typeof InternalFeedbacksRoute
  '/membros': typeof InternalMembrosRoute
  '/visao-geral': typeof InternalVisaoGeralRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/signUp/$invitationId': typeof AuthSignUpInvitationIdRoute
  '/signUp': typeof AuthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_internal': typeof InternalRouteWithChildren
  '/_auth/signIn': typeof AuthSignInRoute
  '/_internal/configuracoes': typeof InternalConfiguracoesRoute
  '/_internal/enviar-feedback': typeof InternalEnviarFeedbackRoute
  '/_internal/feedbacks': typeof InternalFeedbacksRoute
  '/_internal/membros': typeof InternalMembrosRoute
  '/_internal/visao-geral': typeof InternalVisaoGeralRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_auth/signUp/$invitationId': typeof AuthSignUpInvitationIdRoute
  '/_auth/signUp/': typeof AuthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/configuracoes'
    | '/enviar-feedback'
    | '/feedbacks'
    | '/membros'
    | '/visao-geral'
    | '/demo/tanstack-query'
    | '/signUp/$invitationId'
    | '/signUp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signIn'
    | '/configuracoes'
    | '/enviar-feedback'
    | '/feedbacks'
    | '/membros'
    | '/visao-geral'
    | '/demo/tanstack-query'
    | '/signUp/$invitationId'
    | '/signUp'
  id:
    | '__root__'
    | '/'
    | '/_internal'
    | '/_auth/signIn'
    | '/_internal/configuracoes'
    | '/_internal/enviar-feedback'
    | '/_internal/feedbacks'
    | '/_internal/membros'
    | '/_internal/visao-geral'
    | '/demo/tanstack-query'
    | '/_auth/signUp/$invitationId'
    | '/_auth/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InternalRoute: typeof InternalRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AuthSignUpInvitationIdRoute: typeof AuthSignUpInvitationIdRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_internal': {
      id: '/_internal'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_internal/visao-geral': {
      id: '/_internal/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof InternalVisaoGeralRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/membros': {
      id: '/_internal/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof InternalMembrosRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/feedbacks': {
      id: '/_internal/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof InternalFeedbacksRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/enviar-feedback': {
      id: '/_internal/enviar-feedback'
      path: '/enviar-feedback'
      fullPath: '/enviar-feedback'
      preLoaderRoute: typeof InternalEnviarFeedbackRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_internal/configuracoes': {
      id: '/_internal/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof InternalConfiguracoesRouteImport
      parentRoute: typeof InternalRoute
    }
    '/_auth/signIn': {
      id: '/_auth/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signUp/': {
      id: '/_auth/signUp/'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signUp/$invitationId': {
      id: '/_auth/signUp/$invitationId'
      path: '/signUp/$invitationId'
      fullPath: '/signUp/$invitationId'
      preLoaderRoute: typeof AuthSignUpInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InternalRouteChildren {
  InternalConfiguracoesRoute: typeof InternalConfiguracoesRoute
  InternalEnviarFeedbackRoute: typeof InternalEnviarFeedbackRoute
  InternalFeedbacksRoute: typeof InternalFeedbacksRoute
  InternalMembrosRoute: typeof InternalMembrosRoute
  InternalVisaoGeralRoute: typeof InternalVisaoGeralRoute
}

const InternalRouteChildren: InternalRouteChildren = {
  InternalConfiguracoesRoute: InternalConfiguracoesRoute,
  InternalEnviarFeedbackRoute: InternalEnviarFeedbackRoute,
  InternalFeedbacksRoute: InternalFeedbacksRoute,
  InternalMembrosRoute: InternalMembrosRoute,
  InternalVisaoGeralRoute: InternalVisaoGeralRoute,
}

const InternalRouteWithChildren = InternalRoute._addFileChildren(
  InternalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InternalRoute: InternalRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AuthSignUpInvitationIdRoute: AuthSignUpInvitationIdRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
